version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=meu_usuario
      - POSTGRES_PASSWORD=minha_senha
      - POSTGRES_DB=meu_banco
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
